name: GitCheckout
'on': push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  checkout-job:
     runs-on: ubuntu-latest
     steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: Nexus Repo Publish
        run: curl -v -k -u admin -p admin  --upload-file test.txt http://34.45.205.56:8081/devopsmvnhosted/Nexus_Deploy/test.txt
