name: GitCheckout
'on': push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  checkout-job:
     runs-on: ubuntu-latest
     steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: Deploying java 
        run:  |
              sudo apt install default-jdk -y
              sudo apt install default-jre -y
              java -version
           
