name: GitCheckout
'on': push
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
       - name: checkout the repo
         uses: actions/checkout@v4

