name: GitCheckout
'on': push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  checkout-job:
     runs-on: ubuntu-latest
     steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
         serverUrl: 34.171.80.38:8081
         username: admin
         password: admin
         format: txt
         repository: devopsmvnhosted
         coordinates: artifactId='Nexus_Deploy'
         assets: extension=txt
         filename: test
